# Generated by Django 3.0.8 on 2020-07-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('patronymic', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('delivery_datetime', models.DateTimeField(blank=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'created'),
                                                     ('delivered', 'delivered'),
                                                     ('processed', 'processed'),
                                                     ('cancelled', 'cancelled')], max_length=30)),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='productset',
                                                  to='product.ProductSets')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='recipient',
                                                to='product.Recipient')),
            ],
        ),
    ]
