# Generated by Django 3.0.8 on 2020-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='patronymic',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='surname',
            field=models.CharField(max_length=60),
        ),
    ]
